### ISSUE TITLE
De-uglyfi the web pages

### ISSUE THREAD

**Issue by stephanelatil** [stephanelatil/bird-watcher#5]
## TODO

- [x] Add a header with the important pages and an icon
- [x] Add a background color
- [ ] Add nice fonts
- [ ] Add more things on the single-video page like *other* recent videos, videos with similar tags
- [ ] Add filtering and pagination in the video grid page (filter wiith tags/date/length...)
